### ISSUE TITLE
"Go part" fails with go1.11 if go.mod exists in the top-level directory

### ISSUE THREAD

**Issue by anthonyfok** [elopio/go#2]
Hi @elopio,

We have been unable to build the Hugo snap ever since Hugo 0.48 which requires Go 1.11.

As can be seen in the build log snippet below, "Go toolchain2" fails to build when it apparently tries to pull in third-party Go libraries (used by Hugo) which Go compiler itself shouldn't need:

```
'hugo' has prerequisites that need to be staged: go
Preparing to build go 
Building go 
Building Go cmd/dist using /usr/lib/go-1.6.
Building Go toolchain1 using /usr/lib/go-1.6.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
go: golang.org/x/sync@v0.0.0-20180314180146-1d60e4601c6f: unrecognized import path "golang.org/x/sync" (https fetch: no http in bootstrap go command)
go: finding github.com/alecthomas/colour v0.0.0-20160524082231-60882d9e2721
go: finding github.com/BurntSushi/toml v0.0.0-20170626110600-a368813c5e64
...
go: finding github.com/bep/debounce v1.1.0
go: error loading module requirements
go tool dist: FAILED: /build/hugo/parts/go/build/pkg/tool/linux_arm64/go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 1
```

See https://launchpadlibrarian.net/386640495/buildlog_snap_ubuntu_xenial_arm64_hugo-extended-dev_BUILDING.txt.gz for a full log.

It took me a while to figure out that Hugo's Go 1.11 module definition file `go.mod` in the top-level directory is somehow interfering with the building of `go` in the `parts/go/build` directory.  From https://github.com/golang/go/wiki/Modules#how-to-install-and-activate-module-support, Go 1.11's module support can be activated in one of two ways:

> * Invoke the `go` command in a directory outside of the `$GOPATH/src` tree, with a valid `go.mod` file in the current directory or any parent of it and the environment variable `GO111MODULE` unset (or explicitly set to `auto`).
> * Invoke the go command with `GO111MODULE=on` environment variable set.

After much head-scratching, I finally came up with the following workaround:

```yaml
  go:
    # Hugo's go.mod would interfere with the build of Go 1.11 in the
    # parts/go/build/ subdirectory.  Move go.mod out of the way
    # as a workaround.  (Note: 'override-build' does not work here,
    # hence the use of the deprecated 'prepare' keyword.)
    # See https://forum.snapcraft.io/t/go-part-fails-with-go1-11-if-go-mod-exists-in-the-top-level-directory/7546
    prepare: |
      set -x
      ( cd ../../.. && mv -v go.mod go.mod~ )
    source-tag: go1.11
```

And then `go.mod~` is moved back to `go.mod` in the `override-build` step of building `hugo`...  No, not a pretty workaround...

Would modifying the Go ~~plugin~~ part to set the environment variable `GO111MODULE=off` when compiling Go help remedy the situation?  Or would that cause other failures?

Thanks in advance for a better long-term solution to this issue.

Cheers,
Anthony

Please see https://forum.snapcraft.io/t/go-part-fails-with-go1-11-if-go-mod-exists-in-the-top-level-directory/7546 for more discussion.  Many thanks!
